// Generated by CoffeeScript 1.6.3
(function() {
  var codeEditor, currentMode, starterSettings, wrapper;

  starterSettings = {
    value: "var hello = function (nick,to,text) {\n\t// Your code here\n};\n\nbind(\"message\",hello);",
    mode: "javascript",
    theme: "monokai",
    lineNumbers: true,
    lineWrapping: true,
    indentWithTabs: true,
    indentUnit: 4,
    tabMode: "indent",
    showTrailingSpace: true,
    extraKeys: {
      "Ctrl-Q": function(cm) {
        return cm.foldCode(cm.getCursor());
      },
      "Ctrl-Space": "autocomplete"
    },
    foldGutter: true,
    gutters: ["CodeMirror-lint-markers"],
    lint: true,
    highlightSelectionMatches: {
      showToken: /\w/
    }
  };

  codeEditor = wrapper = void 0;

  currentMode = starterSettings.mode;

  CodeMirror.commands.autocomplete = function(cm) {
    return CodeMirror.showHint(cm, CodeMirror.hint.javascript);
  };

  $(document).ready(function() {
    wrapper = document.getElementById("editor");
    return codeEditor = CodeMirror(wrapper, starterSettings);
  });

}).call(this);
